### ISSUE TITLE
Dollar ($) symbols for result variables

### ISSUE THREAD

**Issue by Jameskmonger** [ansteh/difference-json#1]
Hi @ansteh - what was the reason behind choosing to use dollar signs for `$was`, `$set` and `$index`?

**Comment by ansteh** [comment]
Hi @Jameskmonger - i had some concerns in mind:
I introduced them to distinguish module specific keys from input json objects keys. The idea is to have also for e.g. '$set: [here a nested Object where "set" could also be a legal key]'

Why i have  choosen $ ?: Most frameworks like AngularJS or even MongoDB use this kind of declarative '$'+someFrameworkSpecificKey. So to be consistent i have adopted this notation.
